name: links

on: 
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: '0 14 * * 1-5'

jobs:
  check_links:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout source code
      uses: actions/checkout@master

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn add markdown-link-extractor node-fetch

    - name: Check links
      run: |
          JS_FILE=${{ secrets.JS_FILE }}
          JS_FILE=${JS_FILE:-"https://gist.githubusercontent.com/hibuz/831124fa3baf6eb173e99611c03ed6ed/raw/cb34cbf5f127a34eff003cbe8e190019d703db17/links.mjs"}
          curl --silent --output index.mjs ${JS_FILE}
          node index.mjs
